### PR TITLE
Adapt to changes in ScopeSim

### PR DESCRIPTION
**Pull request by teutoburg**
This is in reaction to AstarVienna/Scopesim#423. Apparently I already made these changes a month ago but forgot to push them. Which lead to some minor confusion now on my end, as the local `fh/detectormanager` branch already existed and I ended up giving it the exact same name now. Anyway, I'll merge this in once it passed, because it caused ScopeSim Data to fail [today](https://github.com/AstarVienna/ScopeSim_Data/actions/runs/9729542520/job/26851563842) and [yesterday](https://github.com/AstarVienna/ScopeSim_Data/actions/runs/9721771707/job/26834885291), and the actual change has been discussed and accepted in AstarVienna/Scopesim#423.

### CODE REVIEW

**Comment by hugobuddel** [comment]
I was just going to ask you whether you had a branch ready, and apparently you even had two!

There seem to be three tests that fail: https://github.com/AstarVienna/ScopeSim_Data/actions/runs/9721771707

```
FAILED HAWKI/test_hawki/test_full_package_hawki.py::TestMakeOpticalTrain::test_works_seamlessly_for_hawki_package - AttributeError: 'OpticalTrain' object has no attribute 'detector_arrays'
FAILED Paranal/tests/test_paranal.py::TestParanal::test_flux_scales_with_pixel_scale[J-674] - KeyError: 'x_size_unit'
FAILED Paranal/tests/test_paranal.py::TestParanal::test_flux_scales_with_pixel_scale[H-4693] - KeyError: 'x_size_unit'
FAILED Paranal/tests/test_paranal.py::TestParanal::test_flux_scales_with_pixel_scale[Ks-1026] - KeyError: 'x_size_unit'
FAILED WFC3/test_wfc3/test_full_package_wfc3_ir.py::TestMakeOpticalTrain::test_works_seamlessly_for_wfc3_package - AttributeError: 'OpticalTrain' object has no attribute 'detector_arrays'
= 5 failed, 471 passed, 9 skipped, 63 xfailed, 63 xpassed, 2145 warnings in 642.53s (0:10:42) =
```

Does this also fix the Paranal test? I don't see how that test is even related, but timing wise it seems so.

**Comment by teutoburg** [comment]
> Does this also fix the Paranal test?

Apparently not 😑

**Comment by teutoburg** [comment]
No idea how this passed previously, but whatever, seems to be fixed now...

**Comment by hugobuddel** [comment]
> No idea how this passed previously, but whatever, seems to be fixed now...

That's exactly my thought.. Thanks for fixing it

**Pull request merged**
